sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t marcosanavia/react-app-test -f Dockerfile.dev .

script:
  - docker run -e CI=true marcosanavia/react-app-test npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-2"
  app: "docker"
  env: "production"
  bucket_name: "elasticbeanstalk-eu-west-2-923445559289"
  bucket_path: "docker"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
